#!/usr/bin/env bash
set -euo pipefail

# Generates XCFramework for Greenfield5 core (UniFFI 0.32.1)
# Called from CI (macos-15) after Rust iOS targets built.
# Inputs: core/target/*/release/libgreenfield5_core.a
# Outputs: apps/ios/Greenfield5/Bridge/Generated/Greenfield5Core.xcframework
#          plus Swift bindings (already generated by uniffi-bindgen)
#
# Design invariants (per review):
# - Preserve real UniFFI outputs (greenfield5_coreFFI.h/.modulemap), never replace with placeholders
# - Fail closed if required real artifact missing — no device-for-sim fallback, no empty libs, no manual Info.plist
# - Avoid recursive embedding: use dedicated clean header staging dir, keep XCFramework output outside that input tree
# - No brittle diagnostic pipelines that fail under set -o pipefail (e.g., ls -R | head)

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" || exit 1; pwd)"
IOS_DIR="$(cd -- "$SCRIPT_DIR/.." || exit 1; pwd)"
REPO_ROOT="$(cd -- "$IOS_DIR/../.." || exit 1; pwd)"
CORE_DIR="$REPO_ROOT/core"
GEN_DIR="$IOS_DIR/Greenfield5/Bridge/Generated"
# Dedicated clean header staging outside the Xcode synchronized group to avoid
# Xcode picking up headers as sources and to prevent recursive embedding.
# Previous location GEN_DIR/headers was inside Greenfield5/ (synchronized),
# causing Xcode to include headers as sources and potential recursion.
HEADER_DIR="$CORE_DIR/target/xcframework-headers"

printf 'SCRIPT_DIR=%s\n' "$SCRIPT_DIR"
printf 'IOS_DIR=%s\n' "$IOS_DIR"
printf 'REPO_ROOT=%s\n' "$REPO_ROOT"
printf 'CORE_DIR=%s\n' "$CORE_DIR"
printf 'GEN_DIR=%s\n' "$GEN_DIR"
printf 'HEADER_DIR=%s\n' "$HEADER_DIR"

mkdir -p "$GEN_DIR"

printf 'Listing Rust target outputs (a files):\n'
find "$CORE_DIR/target" -maxdepth 4 -type f -name "libgreenfield5_core.a" -print 2>&1 || true

# Verify Swift bindings exist (generated by previous step)
if [ ! -f "$GEN_DIR/greenfield5.swift" ] && [ ! -f "$GEN_DIR/greenfield5_core.swift" ]; then
  printf 'Swift bindings not found at %s — listing:\n' "$GEN_DIR" >&2
  find "$GEN_DIR" -type f -print 2>&1 || true
  printf 'ERROR: Swift bindings missing. Previous step should have generated them via uniffi-bindgen.\n' >&2
  exit 1
fi

# Verify FFI header and modulemap exist — preserve real UniFFI outputs, do not create placeholders
# UniFFI 0.32.1 generates greenfield5_coreFFI.h and greenfield5_coreFFI.modulemap (observed in CI run 34964374840)
# Older naming greenfield5FFI.* is also accepted for compatibility, but we must not overwrite valid outputs.
if [ ! -f "$GEN_DIR/greenfield5_coreFFI.h" ] && [ ! -f "$GEN_DIR/greenfield5FFI.h" ]; then
  printf 'ERROR: FFI header not found. Expected greenfield5_coreFFI.h or greenfield5FFI.h in %s\n' "$GEN_DIR" >&2
  find "$GEN_DIR" -type f -name "*.h" -print 2>&1 || true
  exit 1
fi

if [ ! -f "$GEN_DIR/greenfield5_coreFFI.modulemap" ] && [ ! -f "$GEN_DIR/greenfield5FFI.modulemap" ]; then
  printf 'ERROR: FFI modulemap not found. Expected greenfield5_coreFFI.modulemap or greenfield5FFI.modulemap in %s\n' "$GEN_DIR" >&2
  find "$GEN_DIR" -type f -name "*.modulemap" -print 2>&1 || true
  exit 1
fi

# Prepare dedicated clean header staging directory
# This avoids recursive embedding where XCFramework output lives inside GEN_DIR and GEN_DIR is used as -headers input.
# Only copy the actual C header and modulemap required by the static library.
rm -rf "${HEADER_DIR:?}"
mkdir -p "$HEADER_DIR"

# Copy header
if [ -f "$GEN_DIR/greenfield5_coreFFI.h" ]; then
  cp "$GEN_DIR/greenfield5_coreFFI.h" "$HEADER_DIR/"
  printf 'Copied %s to %s\n' "$GEN_DIR/greenfield5_coreFFI.h" "$HEADER_DIR"
elif [ -f "$GEN_DIR/greenfield5FFI.h" ]; then
  cp "$GEN_DIR/greenfield5FFI.h" "$HEADER_DIR/"
  printf 'Copied %s to %s\n' "$GEN_DIR/greenfield5FFI.h" "$HEADER_DIR"
fi

# Copy modulemap
if [ -f "$GEN_DIR/greenfield5_coreFFI.modulemap" ]; then
  cp "$GEN_DIR/greenfield5_coreFFI.modulemap" "$HEADER_DIR/"
  printf 'Copied %s to %s\n' "$GEN_DIR/greenfield5_coreFFI.modulemap" "$HEADER_DIR"
elif [ -f "$GEN_DIR/greenfield5FFI.modulemap" ]; then
  cp "$GEN_DIR/greenfield5FFI.modulemap" "$HEADER_DIR/"
  printf 'Copied %s to %s\n' "$GEN_DIR/greenfield5FFI.modulemap" "$HEADER_DIR"
fi

printf 'Header staging dir contents:\n'
find "$HEADER_DIR" -type f -print 2>&1 || true

# Prepare simulator lib directory
SIM_DIR="$CORE_DIR/target/lipo-ios-sim"
mkdir -p "$SIM_DIR"

# Build simulator fat lib if both archs present, otherwise use single arch.
# We do NOT fallback to device lib — that would falsely claim simulator support.
DEVICE_LIB="$CORE_DIR/target/aarch64-apple-ios/release/libgreenfield5_core.a"
SIM_ARM_LIB="$CORE_DIR/target/aarch64-apple-ios-sim/release/libgreenfield5_core.a"
SIM_X86_LIB="$CORE_DIR/target/x86_64-apple-ios-sim/release/libgreenfield5_core.a"
SIM_FAT_LIB="$SIM_DIR/libgreenfield5_core.a"

if [ -f "$SIM_ARM_LIB" ] && [ -f "$SIM_X86_LIB" ]; then
  printf 'Creating fat staticlib for iOS simulator (aarch64 + x86_64)...\n'
  lipo -create "$SIM_ARM_LIB" "$SIM_X86_LIB" -output "$SIM_FAT_LIB"
elif [ -f "$SIM_ARM_LIB" ]; then
  printf 'Found aarch64 simulator lib, using single arch (x86_64 not supported on this toolchain)...\n'
  cp "$SIM_ARM_LIB" "$SIM_FAT_LIB"
elif [ -f "$SIM_X86_LIB" ]; then
  printf 'Found x86_64 simulator lib, using single arch...\n'
  cp "$SIM_X86_LIB" "$SIM_FAT_LIB"
else
  printf 'ERROR: No simulator lib found. Expected at least %s\n' "$SIM_ARM_LIB" >&2
  find "$CORE_DIR/target" -type f -name "*.a" -print 2>&1 || true
  exit 1
fi

if [ ! -f "$DEVICE_LIB" ]; then
  printf 'ERROR: Device lib not found at %s\n' "$DEVICE_LIB" >&2
  find "$CORE_DIR/target" -type f -name "*.a" -print 2>&1 || true
  exit 1
fi

printf 'Simulator lib: %s\n' "$SIM_FAT_LIB"
printf 'Device lib: %s\n' "$DEVICE_LIB"

# Create XCFramework
# Output is GEN_DIR/Greenfield5Core.xcframework which is outside HEADER_DIR (headers = HEADER_DIR), so no recursion.
XCFRAMEWORK="$GEN_DIR/Greenfield5Core.xcframework"
rm -rf "${XCFRAMEWORK:?}"

printf 'Creating XCFramework at %s with headers from %s\n' "$XCFRAMEWORK" "$HEADER_DIR"

# xcodebuild must succeed — no manual Info.plist fallback that could falsely claim architectures
xcodebuild -create-xcframework \
  -library "$DEVICE_LIB" \
  -headers "$HEADER_DIR" \
  -library "$SIM_FAT_LIB" \
  -headers "$HEADER_DIR" \
  -output "$XCFRAMEWORK"

printf 'XCFramework generation done, listing output:\n'
find "$XCFRAMEWORK" -type f -print 2>&1 || true

printf 'Done\n'
