#!/usr/bin/env bash
set -euo pipefail

# Generates XCFramework for Greenfield5 core (UniFFI 0.32.1)
# Called from CI (macos-15) after Rust iOS targets built.
# Inputs: core/target/*/release/libgreenfield5_core.a and Generated/*FFI.h/.modulemap + .swift
# Outputs: apps/ios/Greenfield5/Bridge/Generated/Greenfield5Core.xcframework
#          plus Swift bindings (already generated by uniffi-bindgen)
#
# Design invariants (per review):
# - Preserve real UniFFI outputs (greenfield5_coreFFI.h/.modulemap + greenfield5_core.swift), never replace with placeholders
# - Fail closed if required real artifact missing — no device-for-sim fallback, no empty libs, no manual Info.plist
# - Avoid recursive embedding: use dedicated clean header staging dir OUTSIDE Xcode synchronized group,
#   keep XCFramework output outside that input tree, and ensure staging contains ONLY header + module.modulemap
# - Normalize module metadata per UniFFI/Xcode requirements: rename *FFI.modulemap to module.modulemap
# - Xcode 26 compatibility (UniFFI issue #2917): generated modulemap contains `use "_Builtin_stdbool"` /
#   `use "_Builtin_stdint"` which breaks canImport under Xcode 26/27 because builtin headers belong to system
#   modules (LLVM D159483 default-on Apple). Workaround: strip builtin uses, keep only header + export *.
#   Verified against pinned UniFFI 0.32.1 template (contains Darwin + _Builtin_stdbool + _Builtin_stdint) and
#   upstream issue #2917 (open, affects v0.30.0, v0.31.1, main). Narrowest fix: drop _Builtin_* uses.
# - Keep Swift source separate from C header staging (Swift file stays in Generated/, headers staging is in core/target/)
# - Do not fabricate XCFramework structures or substitute device libs for simulator libs

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" || exit 1; pwd)"
IOS_DIR="$(cd -- "$SCRIPT_DIR/.." || exit 1; pwd)"
REPO_ROOT="$(cd -- "$IOS_DIR/../.." || exit 1; pwd)"
CORE_DIR="$REPO_ROOT/core"
GEN_DIR="$IOS_DIR/Greenfield5/Bridge/Generated"
# Dedicated clean header staging outside the Xcode synchronized group to avoid
# Xcode picking up headers as sources and to prevent recursive embedding.
# Previous location GEN_DIR/headers was inside Greenfield5/ (synchronized),
# causing Xcode to include headers as sources and potential recursion.
HEADER_DIR="$CORE_DIR/target/xcframework-headers"

printf 'SCRIPT_DIR=%s\n' "$SCRIPT_DIR"
printf 'IOS_DIR=%s\n' "$IOS_DIR"
printf 'REPO_ROOT=%s\n' "$REPO_ROOT"
printf 'CORE_DIR=%s\n' "$CORE_DIR"
printf 'GEN_DIR=%s\n' "$GEN_DIR"
printf 'HEADER_DIR=%s\n' "$HEADER_DIR"

mkdir -p "$GEN_DIR"

printf 'Listing Rust target outputs (a files):\n'
find "$CORE_DIR/target" -maxdepth 4 -type f -name "libgreenfield5_core.a" -print 2>&1 || true

# Verify Swift bindings exist (generated by previous step) — preserve real UniFFI output
if [ ! -f "$GEN_DIR/greenfield5.swift" ] && [ ! -f "$GEN_DIR/greenfield5_core.swift" ]; then
  printf 'Swift bindings not found at %s — listing:\n' "$GEN_DIR" >&2
  find "$GEN_DIR" -type f -print 2>&1 || true
  printf 'ERROR: Swift bindings missing. Previous step should have generated them via uniffi-bindgen.\n' >&2
  exit 1
fi

# Verify FFI header and modulemap exist — preserve real UniFFI outputs, do not create placeholders
# UniFFI 0.32.1 generates greenfield5_coreFFI.h and greenfield5_coreFFI.modulemap (observed in CI run 34964374840)
# Older naming greenfield5FFI.* is also accepted for compatibility, but we must not overwrite valid outputs.
HEADER_SRC=""
if [ -f "$GEN_DIR/greenfield5_coreFFI.h" ]; then
  HEADER_SRC="$GEN_DIR/greenfield5_coreFFI.h"
elif [ -f "$GEN_DIR/greenfield5FFI.h" ]; then
  HEADER_SRC="$GEN_DIR/greenfield5FFI.h"
else
  printf 'ERROR: FFI header not found. Expected greenfield5_coreFFI.h or greenfield5FFI.h in %s\n' "$GEN_DIR" >&2
  find "$GEN_DIR" -type f -name "*.h" -print 2>&1 || true
  exit 1
fi

MODULEMAP_SRC=""
if [ -f "$GEN_DIR/greenfield5_coreFFI.modulemap" ]; then
  MODULEMAP_SRC="$GEN_DIR/greenfield5_coreFFI.modulemap"
elif [ -f "$GEN_DIR/greenfield5FFI.modulemap" ]; then
  MODULEMAP_SRC="$GEN_DIR/greenfield5FFI.modulemap"
else
  printf 'ERROR: FFI modulemap not found. Expected greenfield5_coreFFI.modulemap or greenfield5FFI.modulemap in %s\n' "$GEN_DIR" >&2
  find "$GEN_DIR" -type f -name "*.modulemap" -print 2>&1 || true
  exit 1
fi

printf 'Found header: %s\n' "$HEADER_SRC"
printf 'Found modulemap: %s\n' "$MODULEMAP_SRC"
printf 'Original modulemap content:\n'
cat "$MODULEMAP_SRC" || true
echo "---"

# Prepare dedicated clean header staging directory
# This avoids recursive embedding where XCFramework output lives inside GEN_DIR and GEN_DIR is used as -headers input.
# Only copy the actual C header and modulemap required by the static library, with modulemap renamed to module.modulemap
rm -rf "${HEADER_DIR:?}"
mkdir -p "$HEADER_DIR"

# Copy header (preserve real header, fail closed if missing)
HEADER_BASENAME="$(basename "$HEADER_SRC")"
cp "$HEADER_SRC" "$HEADER_DIR/$HEADER_BASENAME"
printf 'Copied header %s to %s\n' "$HEADER_SRC" "$HEADER_DIR/$HEADER_BASENAME"

# Normalize modulemap per UniFFI/Xcode requirements:
# - Must be named module.modulemap inside headers dir for Xcode to detect it
# - Must preserve module name (e.g., greenfield5_coreFFI) from original
# - Xcode 26 workaround: strip `use "_Builtin_stdbool"` and `use "_Builtin_stdint"` which break canImport
#   (UniFFI issue #2917, verified against v0.32.1 template). Keep only header + export *, optionally Darwin.
#   Narrowest fix: drop builtin uses, keep module name and header.

# Extract module name from original modulemap: look for `module <name> {` or `framework module <name> {`
ORIG_MODULE_NAME="$(grep -E '^[[:space:]]*(framework[[:space:]]+)?module[[:space:]]+[A-Za-z0-9_]+' "$MODULEMAP_SRC" | head -n1 | sed -E 's/.*module[[:space:]]+([A-Za-z0-9_]+).*/\1/' || true)"
if [ -z "$ORIG_MODULE_NAME" ]; then
  # Fallback: infer from header basename without .h
  ORIG_MODULE_NAME="$(basename "$HEADER_BASENAME" .h)"
  printf 'WARNING: could not parse module name from modulemap, fallback to %s\n' "$ORIG_MODULE_NAME" >&2
fi
printf 'Original module name: %s\n' "$ORIG_MODULE_NAME"

# Write normalized module.modulemap
# We intentionally drop all `use` declarations that reference builtin modules to support Xcode 26/27.
# If needed, we could keep `use "Darwin"` but safest is header + export * only, which is known to work
# per community guides (Mobile System Design article, boehs.org guide) and avoids builtin issue.
# Reference: https://github.com/mozilla/uniffi-rs/issues/2917
cat > "$HEADER_DIR/module.modulemap" <<EOF
module $ORIG_MODULE_NAME {
    header "$HEADER_BASENAME"
    export *
}
EOF

printf 'Normalized module.modulemap written to %s/module.modulemap:\n' "$HEADER_DIR"
cat "$HEADER_DIR/module.modulemap"
echo "---"

# Verify staging contains ONLY expected files: header + module.modulemap, no Swift, no xcframework, no extra headers
printf 'Header staging dir contents (should be exactly 2 files):\n'
find "$HEADER_DIR" -type f -print 2>&1 || true
STAGING_COUNT="$(find "$HEADER_DIR" -type f | wc -l | tr -d ' ')"
if [ "$STAGING_COUNT" != "2" ]; then
  printf 'ERROR: Header staging should contain exactly 2 files (header + module.modulemap), found %s\n' "$STAGING_COUNT" >&2
  ls -R "$HEADER_DIR" >&2 || true
  exit 1
fi
if [ ! -f "$HEADER_DIR/$HEADER_BASENAME" ]; then
  printf 'ERROR: Header %s missing in staging\n' "$HEADER_BASENAME" >&2
  exit 1
fi
if [ ! -f "$HEADER_DIR/module.modulemap" ]; then
  printf 'ERROR: module.modulemap missing in staging\n' >&2
  exit 1
fi

# Prepare simulator lib directory
SIM_DIR="$CORE_DIR/target/lipo-ios-sim"
mkdir -p "$SIM_DIR"

# Build simulator fat lib if both archs present, otherwise use single arch.
# We do NOT fallback to device lib — that would falsely claim simulator support.
DEVICE_LIB="$CORE_DIR/target/aarch64-apple-ios/release/libgreenfield5_core.a"
SIM_ARM_LIB="$CORE_DIR/target/aarch64-apple-ios-sim/release/libgreenfield5_core.a"
SIM_X86_LIB="$CORE_DIR/target/x86_64-apple-ios-sim/release/libgreenfield5_core.a"
SIM_FAT_LIB="$SIM_DIR/libgreenfield5_core.a"

if [ -f "$SIM_ARM_LIB" ] && [ -f "$SIM_X86_LIB" ]; then
  printf 'Creating fat staticlib for iOS simulator (aarch64 + x86_64)...\n'
  lipo -create "$SIM_ARM_LIB" "$SIM_X86_LIB" -output "$SIM_FAT_LIB"
elif [ -f "$SIM_ARM_LIB" ]; then
  printf 'Found aarch64 simulator lib, using single arch (x86_64 not supported on this toolchain)...\n'
  cp "$SIM_ARM_LIB" "$SIM_FAT_LIB"
elif [ -f "$SIM_X86_LIB" ]; then
  printf 'Found x86_64 simulator lib, using single arch...\n'
  cp "$SIM_X86_LIB" "$SIM_FAT_LIB"
else
  printf 'ERROR: No simulator lib found. Expected at least %s\n' "$SIM_ARM_LIB" >&2
  find "$CORE_DIR/target" -type f -name "*.a" -print 2>&1 || true
  exit 1
fi

if [ ! -f "$DEVICE_LIB" ]; then
  printf 'ERROR: Device lib not found at %s\n' "$DEVICE_LIB" >&2
  find "$CORE_DIR/target" -type f -name "*.a" -print 2>&1 || true
  exit 1
fi

printf 'Simulator lib: %s\n' "$SIM_FAT_LIB"
printf 'Device lib: %s\n' "$DEVICE_LIB"

# Create XCFramework
# Output is GEN_DIR/Greenfield5Core.xcframework which is outside HEADER_DIR (headers = HEADER_DIR), so no recursion.
XCFRAMEWORK="$GEN_DIR/Greenfield5Core.xcframework"
rm -rf "${XCFRAMEWORK:?}"

printf 'Creating XCFramework at %s with headers from %s\n' "$XCFRAMEWORK" "$HEADER_DIR"

# xcodebuild must succeed — no manual Info.plist fallback that could falsely claim architectures
xcodebuild -create-xcframework \
  -library "$DEVICE_LIB" \
  -headers "$HEADER_DIR" \
  -library "$SIM_FAT_LIB" \
  -headers "$HEADER_DIR" \
  -output "$XCFRAMEWORK"

printf 'XCFramework generation done, listing output:\n'
find "$XCFRAMEWORK" -type f -print 2>&1 || true

# Verify XCFramework contains expected slices and headers with normalized modulemap
if [ ! -f "$XCFRAMEWORK/Info.plist" ]; then
  printf 'ERROR: XCFramework Info.plist missing at %s\n' "$XCFRAMEWORK/Info.plist" >&2
  exit 1
fi
# Check that each slice contains module.modulemap and header
for slice in "$XCFRAMEWORK"/*; do
  if [ -d "$slice" ]; then
    if [ ! -f "$slice/Headers/$HEADER_BASENAME" ]; then
      printf 'ERROR: Header missing in slice %s\n' "$slice" >&2
      find "$slice" -type f -print >&2 || true
      exit 1
    fi
    if [ ! -f "$slice/Headers/module.modulemap" ]; then
      printf 'ERROR: module.modulemap missing in slice %s (expected normalized name)\n' "$slice" >&2
      find "$slice" -type f -print >&2 || true
      exit 1
    fi
    printf 'Slice %s OK, modulemap content:\n' "$slice"
    cat "$slice/Headers/module.modulemap" || true
  fi
done

printf 'Done\n'
