//! Shared Greenfield5 core.
//!
//! This crate holds the product logic that Android and iOS must agree on
//! byte-for-byte: the session role/state model today, and — per
//! [ADR-0005](https://github.com/anthracite-labs/Greenfield5/blob/main/docs/decisions/0005-rust-native-moq-iroh-architecture.md)
//! — pairing/admission, protocol models, and MoQ-over-Iroh transport
//! orchestration as those land in follow-up work.
//!
//! # Ownership boundaries (ADR-0005)
//!
//! The Rust core owns session state and transitions. Platform screen capture,
//! permissions, lifecycle, hardware media, LAN/Wi-Fi Aware integration, and UI
//! remain native (Kotlin/Compose on Android, Swift/SwiftUI on iOS) and are
//! deliberately *not* abstracted here.
//!
//! # The seam
//!
//! [`seam`] is the narrow facade the native shells will consume once the
//! native↔Rust bridge is wired (follow-up issue). It speaks in stable integer
//! wire codes so the eventual FFI mechanism — UniFFI or another pinned choice,
//! decided in that follow-up — can export this surface without UI code ever
//! depending on Rust types or transport internals.
//!
//! # UniFFI bridge (ADR-0007)
//!
//! [`uniffi_api`] exposes the same session model via UniFFI proc-macros,
//! pinned at 0.32.1 (mozilla/uniffi-rs tags v0.32.1 35a47433, v0.32.0 5c7b739).
//! The existing [`seam`] remains the stable u8-code contract; the UniFFI
//! layer delegates to it and does not expand session semantics.
//!
//! # Verification
//!
//! `cargo test` (toolchain pinned by `rust-toolchain.toml`); CI runs
//! `cargo fmt --check`, `cargo clippy -- -D warnings`, and `cargo test` in
//! `.github/workflows/stack.yml`.

// The unsafe boundary — what the compiler actually enforces (ADR-0007).
//
// `#![allow(unsafe_code)]` at the crate root is load-bearing, not cosmetic:
// UniFFI's `setup_scaffolding!()` expansion emits `pub unsafe extern "C" fn`
// FFI shims (uniffi-rs v0.32.1, uniffi_macros/src/setup_scaffolding.rs), and a
// lint attribute cannot be scoped to it — `#[allow(unsafe_code)]` placed
// directly on the macro invocation was reported as `unused_attributes` under
// `-D warnings` with Rust 1.98 (commit d318aa9), i.e. it never reached the
// expanded items. The scaffolding also cannot move into a submodule to gain a
// module-scoped allow; see the note at the invocation site below.
//
// Enforced shape, stated precisely:
//   - `unsafe` is DENIED in `seam` and `session` (all handwritten product logic).
//   - `unsafe` is ALLOWED in `uniffi_api` (UniFFI derive/export expansions) and
//     at the crate root (the scaffolding expansion only).
//   - Consequence: a NEW module that omits its own `#[deny(unsafe_code)]`
//     inherits the crate-level allow. This boundary is therefore deny-by-
//     declaration, not deny-by-default. Every module added to this file must
//     carry an explicit `#[deny(unsafe_code)]` unless it too is UniFFI macro
//     output.
//
// No handwritten `unsafe` exists anywhere in this crate; every unsafe item is
// generated by a pinned UniFFI proc-macro. `#![allow(unused_attributes)]`
// remains for the same macro-expansion reason as above, and
// `#![allow(missing_docs)]` covers generated items that carry no doc comments
// (`seam`/`session` re-deny it).
#![allow(unsafe_code)]
#![allow(unused_attributes)]
#![allow(missing_docs)]

#[deny(unsafe_code)]
#[deny(missing_docs)]
pub mod seam;
#[deny(unsafe_code)]
#[deny(missing_docs)]
pub mod session;
#[allow(unsafe_code)]
#[allow(missing_docs)]
pub mod uniffi_api;

/// The crate version, as compiled in (`CARGO_PKG_VERSION`).
pub fn version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

// UniFFI scaffolding — proc-macro only, no UDL. Placed at crate root per
// upstream docs (https://mozilla.github.io/uniffi-rs/latest/proc_macro/index.html),
// and it must stay there: the expansion emits `pub struct UniFfiTag`, which
// UniFFI's derive output references as `crate::UniFfiTag` (uniffi-rs v0.32.1 —
// uniffi_macros/src/enum_.rs:255 and record.rs:121 expand
// `ffi_converter_rust_buffer_lift_and_lower!(crate::UniFfiTag)`, and
// uniffi_macros/src/ffiops.rs has ~15 further lift/lower sites). Moving the
// invocation into a submodule to buy a module-scoped `#[allow(unsafe_code)]`
// would break that path, and would leave the `#[macro_export]`ed
// `uniffi_reexport_scaffolding!` resolving `$crate::uniffi_reexport_hack` to an
// item that is no longer at the crate root. The crate-level allow documented
// above is therefore the narrowest allowance that compiles against this pin.
uniffi::setup_scaffolding!();
