// Generated by UniFFI — this is a placeholder that will be overwritten by CI
// with real bindings from `cargo run --bin uniffi-bindgen`. It provides the
// same public API as the real generated file so the Android project compiles
// without a Rust toolchain (foundation gate), while CI proves the real bridge.
//
// Source of truth: core/src/uniffi_api.rs (UniFFI 0.32.1)
// This stub mirrors that API in pure Kotlin for local builds; the real
// generated file uses JNA to call libgreenfield5_core.so.
//
// Error naming must mirror the real generator, not the Rust source: UniFFI's
// Kotlin oracle rewrites an error enum whose Rust name ends in `Error` to
// `*Exception` (convert_error_suffix), so Rust `BridgeError` is Kotlin
// `BridgeException`. Keeping the stub's name identical is what lets the app
// compile against either this fallback or the CI-generated bindings.

@file:Suppress("all")
package uniffi.greenfield5

// Keep JNA symbols from R8 — real generated file uses JNA, stub does not but
// we keep the same keep rules.
enum class Role {
    SENDER,
    VIEWER
}

enum class ConnectionMode {
    LOCAL,
    DIRECT,
    INTERNET
}

enum class SessionState {
    IDLE,
    AWAITING_PEER,
    AWAITING_APPROVAL,
    ACTIVE,
    SHARING_INTERRUPTED,
    ENDED
}

enum class SessionCommand {
    START_PAIRING,
    REQUEST_JOIN,
    PEER_REQUESTED_JOIN,
    APPROVE_VIEWER,
    APPROVAL_RECEIVED,
    CAPTURE_STARTED,
    CAPTURE_STOPPED,
    END
}

sealed class BridgeException : Exception() {
    data class UnknownRoleCode(val code: UByte) : BridgeException()
    data class UnknownModeCode(val code: UByte) : BridgeException()
    data class UnknownCommandCode(val code: UByte) : BridgeException()
    data class RoleMismatch(val expected: Role) : BridgeException()
    data class InvalidTransition(val state: SessionState, val command: SessionCommand) : BridgeException()
    object ViewerAlreadyConnected : BridgeException()
    object SessionEnded : BridgeException()
}

// Pure-Kotlin implementation of the session state machine, mirroring
// core/src/session.rs logic for local builds. Real generated bindings
// delegate to Rust via JNA.

class GreenfieldSession(
    private val role: Role,
    private val mode: ConnectionMode
) {
    private var state: SessionState = SessionState.IDLE
    private var viewerConnected: Boolean = false
    private var viewerApproved: Boolean = false

    companion object {
        fun `new`(role: Role, mode: ConnectionMode): GreenfieldSession {
            return GreenfieldSession(role, mode)
        }

        fun fromCodes(roleCode: UByte, modeCode: UByte): GreenfieldSession {
            val r = when (roleCode.toInt()) {
                0 -> Role.SENDER
                1 -> Role.VIEWER
                else -> throw BridgeException.UnknownRoleCode(roleCode)
            }
            val m = when (modeCode.toInt()) {
                0 -> ConnectionMode.LOCAL
                1 -> ConnectionMode.DIRECT
                2 -> ConnectionMode.INTERNET
                else -> throw BridgeException.UnknownModeCode(modeCode)
            }
            return GreenfieldSession(r, m)
        }
    }

    fun role(): Role = role
    fun mode(): ConnectionMode = mode
    fun state(): SessionState = state
    fun viewerApproved(): Boolean = viewerApproved

    fun roleCode(): UByte = when (role) {
        Role.SENDER -> 0u
        Role.VIEWER -> 1u
    }

    fun connectionModeCode(): UByte = when (mode) {
        ConnectionMode.LOCAL -> 0u
        ConnectionMode.DIRECT -> 1u
        ConnectionMode.INTERNET -> 2u
    }

    fun stateCode(): UByte = when (state) {
        SessionState.IDLE -> 0u
        SessionState.AWAITING_PEER -> 1u
        SessionState.AWAITING_APPROVAL -> 2u
        SessionState.ACTIVE -> 3u
        SessionState.SHARING_INTERRUPTED -> 4u
        SessionState.ENDED -> 5u
    }

    @Throws(BridgeException::class)
    fun apply(command: SessionCommand): SessionState {
        if (state == SessionState.ENDED) throw BridgeException.SessionEnded

        val next = when (command) {
            SessionCommand.END -> SessionState.ENDED
            SessionCommand.START_PAIRING -> {
                if (role != Role.SENDER) throw BridgeException.RoleMismatch(Role.SENDER)
                if (state != SessionState.IDLE) throw BridgeException.InvalidTransition(state, command)
                SessionState.AWAITING_PEER
            }
            SessionCommand.REQUEST_JOIN -> {
                if (role != Role.VIEWER) throw BridgeException.RoleMismatch(Role.VIEWER)
                if (state != SessionState.IDLE) throw BridgeException.InvalidTransition(state, command)
                SessionState.AWAITING_APPROVAL
            }
            SessionCommand.PEER_REQUESTED_JOIN -> {
                if (role != Role.SENDER) throw BridgeException.RoleMismatch(Role.SENDER)
                if (viewerConnected) throw BridgeException.ViewerAlreadyConnected
                if (state != SessionState.AWAITING_PEER) throw BridgeException.InvalidTransition(state, command)
                viewerConnected = true
                SessionState.AWAITING_APPROVAL
            }
            SessionCommand.APPROVE_VIEWER -> {
                if (role != Role.SENDER) throw BridgeException.RoleMismatch(Role.SENDER)
                if (state != SessionState.AWAITING_APPROVAL) throw BridgeException.InvalidTransition(state, command)
                viewerApproved = true
                SessionState.ACTIVE
            }
            SessionCommand.APPROVAL_RECEIVED -> {
                if (role != Role.VIEWER) throw BridgeException.RoleMismatch(Role.VIEWER)
                if (state != SessionState.AWAITING_APPROVAL) throw BridgeException.InvalidTransition(state, command)
                viewerApproved = true
                SessionState.ACTIVE
            }
            SessionCommand.CAPTURE_STARTED -> {
                if (state != SessionState.SHARING_INTERRUPTED) throw BridgeException.InvalidTransition(state, command)
                SessionState.ACTIVE
            }
            SessionCommand.CAPTURE_STOPPED -> {
                if (state != SessionState.ACTIVE) throw BridgeException.InvalidTransition(state, command)
                SessionState.SHARING_INTERRUPTED
            }
        }
        state = next
        return next
    }

    @Throws(BridgeException::class)
    fun sendCommand(commandCode: UByte): UByte {
        val cmd = when (commandCode.toInt()) {
            0 -> SessionCommand.START_PAIRING
            1 -> SessionCommand.REQUEST_JOIN
            2 -> SessionCommand.PEER_REQUESTED_JOIN
            3 -> SessionCommand.APPROVE_VIEWER
            4 -> SessionCommand.APPROVAL_RECEIVED
            5 -> SessionCommand.CAPTURE_STARTED
            6 -> SessionCommand.CAPTURE_STOPPED
            7 -> SessionCommand.END
            else -> throw BridgeException.UnknownCommandCode(commandCode)
        }
        return when (apply(cmd)) {
            SessionState.IDLE -> 0u
            SessionState.AWAITING_PEER -> 1u
            SessionState.AWAITING_APPROVAL -> 2u
            SessionState.ACTIVE -> 3u
            SessionState.SHARING_INTERRUPTED -> 4u
            SessionState.ENDED -> 5u
        }
    }
}

fun coreVersion(): String = "0.1.0-stub"
fun roleSenderCode(): UByte = 0u
fun roleViewerCode(): UByte = 1u
fun modeLocalCode(): UByte = 0u
fun modeDirectCode(): UByte = 1u
fun modeInternetCode(): UByte = 2u
